# Generated by Django 4.2 on 2023-04-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_alter_user_birthdate"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="birthdate",
            field=models.DateField(null=True),
        ),
    ]
