# Generated by Django 4.2 on 2023-04-23 21:28

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("movies", "0004_movieorder"),
    ]

    operations = [
        migrations.AddField(
            model_name="movie",
            name="users",
            field=models.ManyToManyField(
                related_name="movie_orders",
                through="movies.MovieOrder",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
